### PR TITLE
 implement-queue-using-stacks-rotimidokun.js

### PR DESCRIPTION
**Pull request by rotimidokun**
This is my entry solution for leetcode #232. Please review solution and merge.

### CODE REVIEW

**Review by IAMebonyhope — CHANGES_REQUESTED** [review]
can you rename the file with "implement-queue-using-stacks-rotimidokun.js"

**Comment by rotimidokun** [comment]
@IAMebonyhope File has been renamed. Thanks

**Review by IAMebonyhope — APPROVED** [review]

**Comment by IAMebonyhope** [comment]
Thanks for contributing your solution

**Comment by rotimidokun** [comment]
My absolute pleasure. 

Thank you Hope for the opportunity.

**Pull request merged**
