### PR TITLE
Sorting algorithms implementation

### PR DESCRIPTION
**Pull request by aishat-ajose**
Added python implemention of insertion, selection and merge sort

### CODE REVIEW

**Review by IAMebonyhope — COMMENTED** [review]
can you rename the files to [sorting-algorithm]-[implementation]-ajoseaishat.py 
e.g: insertion-sort-implementation-ajoseaishat.py

**Review by IAMebonyhope — CHANGES_REQUESTED** [review]
rename files to include your username

**Comment by aishat-ajose** [comment]
> can you rename the files to [sorting-algorithm]-[implementation]-ajoseaishat.py e.g: insertion-sort-implementation-ajoseaishat.py

I have done that. Thanks

**Review by IAMebonyhope — APPROVED** [review]

**Comment by IAMebonyhope** [comment]
Thanks for contributing those sorting algorithm implementations

**Pull request merged**
